### PR TITLE
Readme addons and script to explode and write csv

### PR DESCRIPTION
**Pull request by camallen**
maybe useful...

### CODE REVIEW

**Comment by marten** [comment]
The shell script I'm not sure about. If you install this as a pip package, pip will generate an executable that takes a filename and spits to STDOUT. Maybe adding `panoptes-expand path/to/classifications.csv > expanded_classifications.csv` to the README would add the same? My goal was always to provide a CLI script through Python; where param parsing if/when needed is easier and compatibility with Windows is good.

**Comment by camallen** [comment]
Cool - feel free to close this then. Having good docs around this and simple exectuables is key for researchers.

**Comment by marten** [comment]
I've stolen your Python snippet, making it clearer what comes out (a pandas df) is a good thing too.

**Comment by marten** [comment]
And this should be pushed on PyPI and installable as per the readme. Don't have much experience with Python on Windows, not sure how people usually get a shell that can run `pip` so I'm open to a PR for that. Good thing about setup.py's generated CLI scripts are that they are .exe files put on the PATH in Windows, so you can indeed easily call them (and redirection should be the same as on POSIX afaik)

**Comment by camallen** [comment]
Sweet, as long as a novice user can come along and use the readme to get the exploded csv file then we're good.

**Comment by marten** [comment]
In theory, yep. In practice there's bound to be something missing that will only be discovered when the first novice user actually comes along ;)

**Pull request closed without merging**
